 // Source code is unavailable, and was generated by the Fernflower decompiler.
package thaumrev.block;

import net.minecraft.block.Block;
import net.minecraft.block.BlockSlab;
import net.minecraft.item.ItemSlab;
import thaumrev.config.ConfigLibrary;

public class BlockCosmeticSlabQuartzItem extends ItemSlab {
  public BlockCosmeticSlabQuartzItem(Block block) {
    super(
      block,
      (BlockSlab) ConfigLibrary.blockSlabInfusedQuartz,
      (BlockSlab) ConfigLibrary.blockSlabDoubleInfusedQuartz,
      false
    );

    this.setHasSubtypes(true);
  }
}
